### PR TITLE
[misc] add a build pipeline

### PR DESCRIPTION
**Pull request by das7pad**
For https://github.com/overleaf/issues/issues/3017
CI: https://github.com/overleaf/google-ops/pull/1229

Artifacts are stored in https://github.com/overleaf/ace-builds -- see https://github.com/overleaf/ace-builds/tags
Installing/developing locally is achieved via a tar-ball install:
- `ace$ make local`
- `dev-env$ cp ../path-to-ace/local.tar.gz web/`
- `dev-env$ bin/npm web install ./local.tar.gz` 

Updating ace in web (after landing https://github.com/overleaf/web-internal/pull/3176):
- rebase this commit among all the other overleaf commits upon a release -- e.g. see the branch https://github.com/overleaf/ace/tree/jpa-build-pipeline-v1.4.10
- push to github -- triggers a cloudbuild
- copy the url emitted in the `package_url` stage https://console.cloud.google.com/cloud-build/builds/f54c7fee-d988-469e-8a00-eb03a4ceb578;step=6?project=overleaf-ops
  (or compose it manually)
- `dev-env$ bin/npm web install https://github.com/overleaf/ace-builds/archive/v1.4...`

### CODE REVIEW

**Review by 40thieves — APPROVED** [review]
LGTM :shipit:

Can you update [the documentation for updating Ace](https://github.com/overleaf/write_latex/wiki/Upgrading-Ace) with the new process? My main concern is making it clear how the pipeline works, so adding some docs would address this.

**Comment by alismith-dev** [comment]
Also, just to check, this

> rebase this commit among all the other overleaf commits upon a release -- e.g. see the branch https://github.com/overleaf/ace/tree/jpa-build-pipeline-v1.4.10

Should now be updated to v1.4.12?

**Comment by das7pad** [comment]
> Also, just to check, this
> 
> > rebase this commit among all the other overleaf commits upon a release -- e.g. see the branch https://github.com/overleaf/ace/tree/jpa-build-pipeline-v1.4.10
> 
> Should now be updated to v1.4.12?

This was an example for another version and that rebasing one commit (for the 1.4.10 branch https://github.com/overleaf/ace/commit/9b56d448f4d21cacfa4bdc3973992407df0cc778) is sufficient to get [a new release](https://console.cloud.google.com/cloud-build/builds/f54c7fee-d988-469e-8a00-eb03a4ceb578;step=6?project=overleaf-ops) out.

**Comment by das7pad** [comment]
RE https://github.com/overleaf/web-internal/pull/3176#discussion_r490803711 I added a `version` file into the build/ output directory and [force-pushed](https://github.com/overleaf/ace/compare/e9e1a7994c7203ddd537478c0f8ae2240e1f8b39..69aace50e6796d42116f8f96e19d2468d8a88af9).

**Pull request merged**
